apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSmphd2dXMndrK0l3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBM01qa3hPVEEwTXpaYUZ3MHpOREEzTWpjeE9UQTVNelphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURBbXJHSUdYYlNhMVgyZTZyeDBHYjJtTjk1SkNiQ21MY1dHS3VrZmp3U3BHekZqeGNmSEwrOEdqa3kKYWhwYmJKSWdPeHpnV0wxOFdNNzNJZUU2MFU4cFkvaFVLYUpvVFg1alhjVHAvRGJxdFlZOUdaSEt0N1o4QlVQRQpldndXbGFyRFltYTBHT0NVZm1vTzFhM1JyNUVia2FQTnVxVkFnQ1g1M0FyYmNvbEQ5Tk5yclhTUEpUa0t2QVIyClRIbHJwRmFHcE9DV2svR3YrTkVIKzgvNHRsRjlwUlJHZHErenhOcCsvdGg4b1RkL2FZa3ZIMWdsd25MRHNCMkkKcmpsSzltc21NcW4vNlIvYzF2ZzJyMitvck1NVDBDTlJSWjB5YzdybUJlVlRiQ2x3VURwcjNxdmFRUk5jaG1JLwpYR21BMEJMTm5kbmNNZGtlajdQOTBDbk9TTk4zQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSQkJXTXhFYXhtQzRxcE8xY2Y3bDIxcEFtREN6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkJHdXRZL1A4aAp5OUx5Q0dzM3Z6bWZpbU02YjF3NDNDSlZqZVkzRVlYcFZTSTlLMXRZVk9lNlMwamhNVjFmdWg5QkxwdG95MzZhClBhUkJuZGltakhmZExsN1lQbkJQUm9oVjFWRnBweS9rTE9iclVVZEtnNExuUUQwSDhpLzVWTXNrdEQwSjY1USsKRjN1SndsdmVwdEhoei9RS29NRHdrN1ppL2dRYk5yMWd0bndENm1UY1VvZDZIZjNZRm9KQmtDUTk5N1ZjYjVESQpXQTBUSjZkaEpnT0FrNUxPODZ2ek1NQjdIUnJId2xjYnBNSUtxTWVBYThEdjVJenpVZFhZODlQcUZxREg4bDdFCjR0bzNPeW01azAxL0NPeWlwTXd2MHByYlJHMGUwWnVuSlFZTVduclh3UjlEemJuNU5aT2RJMXBNNE5GMXlpQVAKUHBLNW12RnU3aGxSCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://BF98936C7C74560F33F6E27420467B77.gr7.us-west-2.eks.amazonaws.com
  name: arn:aws:eks:us-west-2:676894657875:cluster/qa10-msvin
contexts:
- context:
    cluster: arn:aws:eks:us-west-2:676894657875:cluster/qa10-msvin
    user: arn:aws:eks:us-west-2:676894657875:cluster/qa10-msvin
  name: arn:aws:eks:us-west-2:676894657875:cluster/qa10-msvin
current-context: arn:aws:eks:us-west-2:676894657875:cluster/qa10-msvin
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-west-2:676894657875:cluster/qa10-msvin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - qa10-msvin
      - --output
      - json
      command: aws
